version: "2"

linters:
  enable:
    - staticcheck
    - gochecknoinits
    - gochecknoglobals
    - govet
    - errcheck
    - ineffassign
    - unused
    - errorlint
    - nolintlint

  settings:
    staticcheck:
      checks:
        - all
        # examples:
        # - ST1003   # naming conventions
        # - ST1000   # package comments
