// Package audit reads, parses and correlates Linux kernel audit records
// delivered over the NETLINK_AUDIT multicast socket.
//
// The package is deliberately self-contained: the audit wire format is one of
// the core security surfaces of SauronAgent, so parsing stays under our own
// control and is covered by unit and fuzz tests rather than delegated to an
// external dependency.
package audit

import (
	"fmt"
	"time"
)

//go:generate true

// RawMessage is a single netlink message carrying one audit record, as read
// off the multicast socket and before any text parsing has happened.
//
// Data is owned by the receiver: the netlink reader always hands out a copy so
// that the receive buffer can be reused for the next datagram.
type RawMessage struct {
	// Type is the netlink message type, which for audit traffic is the
	// audit record type (AUDIT_SYSCALL, AUDIT_EXECVE, ...).
	Type RecordType

	// Data is the record body, i.e. the text following "type=NAME ".
	// The kernel delivers it as an ASCII string without a trailing newline,
	// typically starting with "audit(<secs>.<msecs>:<serial>): ".
	Data []byte

	// Received is the wall-clock time the agent read the message. It is used
	// only as a fallback when the record itself carries no usable timestamp.
	Received time.Time
}

// Record is one parsed Linux audit record.
//
// A single logical operation usually produces several records that share an
// AuditID; the correlator groups them, and the normalizer turns each group
// into one Event.
type Record struct {
	// Type is the numeric audit record type.
	Type RecordType

	// TypeName is the canonical auditd name for Type, e.g. "SYSCALL".
	// Unknown types are rendered as UNKNOWN[nnnn].
	TypeName string

	// Timestamp is the kernel-supplied event time with millisecond precision.
	Timestamp time.Time

	// Serial is the kernel audit event serial number.
	Serial uint64

	// AuditID is the full kernel event identifier, "<secs>.<msecs>:<serial>".
	// Every record belonging to the same logical event carries the same value.
	AuditID string

	// Fields holds the record's key=value pairs. Values are stored decoded:
	// surrounding double quotes are removed and hex-encoded values are decoded
	// to their raw bytes. Keys appear exactly as the kernel emitted them.
	Fields map[string]string

	// Raw is the complete original record text, reconstructed as
	// "type=NAME msg=audit(...): ...". It is preserved verbatim so that
	// normalization never destroys the kernel-generated evidence.
	Raw string
}

// RecordTypeName returns the canonical auditd text name for t. Types that are
// not in the table are rendered as UNKNOWN[nnnn], matching auditd behaviour,
// so an unrecognised record is still reported rather than silently dropped.
func RecordTypeName(t RecordType) string {
	if name, ok := recordTypeNames[t]; ok {
		return name
	}
	return fmt.Sprintf("UNKNOWN[%d]", uint16(t))
}

// String implements fmt.Stringer.
func (t RecordType) String() string { return RecordTypeName(t) }

// RecordTypeByName resolves a canonical auditd name such as "SYSCALL" to its
// numeric type. The lookup is case-sensitive, matching the kernel's spelling.
func RecordTypeByName(name string) (RecordType, bool) {
	t, ok := recordTypesByName[name]
	return t, ok
}

// recordTypesByName is the reverse of recordTypeNames, built once at init.
var recordTypesByName = func() map[string]RecordType {
	m := make(map[string]RecordType, len(recordTypeNames))
	for t, name := range recordTypeNames {
		m[name] = t
	}
	return m
}()

// IsUserMessage reports whether t is in either user-space message range.
// Records in these ranges are generated by privileged user-space programs
// (login, sudo, sshd, PAM) rather than by the kernel's syscall auditing.
func (t RecordType) IsUserMessage() bool {
	return (t >= TypeFirstUserMsg && t <= TypeLastUserMsg) ||
		(t >= TypeFirstUserMsg2 && t <= TypeLastUserMsg2)
}

// IsKernelAnomaly reports whether t is a kernel-generated anomaly record.
func (t RecordType) IsKernelAnomaly() bool {
	return t >= TypeFirstKernAnomMsg && t <= TypeLastKernAnomMsg
}

// IsControl reports whether t belongs to the audit control range (1000-1099).
// Control messages are replies to configuration requests rather than audit
// events, with the exception of AUDIT_LOGIN which does report a real event.
func (t RecordType) IsControl() bool {
	return t >= TypeGet && t < TypeFirstUserMsg
}
